### ISSUE TITLE
Exclude all Jupyter notebook projects instead of manually controlling the list

### ISSUE THREAD

**Issue by arunsathiya** [arunsathiya/arunsathiya#2]
Exclude all Jupyter notebook projects instead of manually controlling the list like https://github.com/arunsathiya/arunsathiya/commit/c0b108cef279b48bc9b7f9837d75be3b88e3f4f7. Perhaps some kind of GitHub action workflow that automates finding and committing the repositories?

**Comment by sharunkumar** [comment]
You can exclude by language: https://github.com/sharunkumar/sharunkumar/commit/b2454f1acc0f8fc01c7154d58e7b1c60823179a2

**Comment by arunsathiya** [comment]
`&hide=` param works great, thanks! Had to URI-escape the values too: https://github.com/arunsathiya/arunsathiya/commit/cc7b6e87dcbdeebfaa04720e62ced43e4c5eb953
